services:
  snake-game:
    build: .
    container_name: ${CONTAINER_NAME:-snake-game-app}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - snake-network

networks:
  snake-network:
    driver: bridge
